# Generated by Django 5.2.4 on 2025-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('Cooktime', models.IntegerField()),
                ('mealType', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
