# Generated by Django 5.2.4 on 2025-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What meal do you want to prepare?', max_length=100)),
                ('calories', models.IntegerField()),
                ('time_required', models.IntegerField(help_text='Time in minutes')),
                ('ingredients', models.ManyToManyField(to='Recipes.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
